In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#import the libraries
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/CSE 360 - Deep Learning/Datasets/HR_comma_sep.csv")
data.head(5)

   satisfaction_level  last_evaluation  ...  sales  salary
0                0.38             0.53  ...  sales     low
1                0.80             0.86  ...  sales  medium
2                0.11             0.88  ...  sales  medium
3                0.72             0.87  ...  sales     low
4                0.37             0.52  ...  sales     low

[5 rows x 10 columns]

In [ ]:
print(data.shape)

(14999, 10)

In [ ]:
df1=['sales','salary']
df_final = pd.get_dummies(data,columns = df1,drop_first = True)
df_final.head(3)

   satisfaction_level  last_evaluation  ...  salary_low  salary_medium
0                0.38             0.53  ...           1              0
1                0.80             0.86  ...           0              1
2                0.11             0.88  ...           0              1

[3 rows x 19 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X = df_final.drop(['left'],axis = 1).values
y = df_final['left'].values
print(X.shape)
print(y.shape)

(14999, 18)
(14999,)

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(10499, 18)
(4500, 18)
(10499,)
(4500,)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

In [ ]:
#Build the model
model = Sequential()
model.add(Dense(128,kernel_initializer="uniform",input_dim = 18,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dense(1,kernel_initializer="uniform",activation='sigmoid'))

In [ ]:
#model compile
model.compile(optimizer='adam',loss = 'binary_crossentropy',metrics=['accuracy'])

In [ ]:
#fit the model
model.fit(X_train,y_train,epochs = 100,batch_size = 32)

Epoch 1/100
329/329 [==============================] - 2s 4ms/step - loss: 0.3040 - accuracy: 0.8780
Epoch 2/100
329/329 [==============================] - 1s 3ms/step - loss: 0.1626 - accuracy: 0.9532
Epoch 3/100
329/329 [==============================] - 1s 3ms/step - loss: 0.1543 - accuracy: 0.9534
Epoch 4/100
329/329 [==============================] - 1s 2ms/step - loss: 0.1451 - accuracy: 0.9570
Epoch 5/100
329/329 [==============================] - 1s 2ms/step - loss: 0.1405 - accuracy: 0.9579
Epoch 6/100
329/329 [==============================] - 1s 2ms/step - loss: 0.1320 - accuracy: 0.9609
Epoch 7/100
329/329 [==============================] - 1s 2ms/step - loss: 0.1267 - accuracy: 0.9614
Epoch 8/100
329/329 [==============================] - 1s 2ms/step - loss: 0.1195 - accuracy: 0.9644
Epoch 9/100
329/329 [==============================] - 1s 2ms/step - loss: 0.1131 - accuracy: 0.9652
Epoch 10/100
329/329 [==============================] - 1s 2ms/step - loss: 0.1098 - accuracy: 0.9663
Epoch 11/100
329/329 [==============================] - 1s 2ms/step - loss: 0.1034 - accuracy: 0.9686
Epoch 12/100
329/329 [==============================] - 1s 2ms/step - loss: 0.1012 - accuracy: 0.9685
Epoch 13/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0970 - accuracy: 0.9695
Epoch 14/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0931 - accuracy: 0.9709
Epoch 15/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0909 - accuracy: 0.9723
Epoch 16/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0879 - accuracy: 0.9735
Epoch 17/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0867 - accuracy: 0.9730
Epoch 18/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0832 - accuracy: 0.9737
Epoch 19/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0793 - accuracy: 0.9749
Epoch 20/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0792 - accuracy: 0.9750
Epoch 21/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0769 - accuracy: 0.9757
Epoch 22/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0742 - accuracy: 0.9770
Epoch 23/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0723 - accuracy: 0.9776
Epoch 24/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0709 - accuracy: 0.9776
Epoch 25/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0693 - accuracy: 0.9790
Epoch 26/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0679 - accuracy: 0.9779
Epoch 27/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0647 - accuracy: 0.9789
Epoch 28/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0625 - accuracy: 0.9803
Epoch 29/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0638 - accuracy: 0.9796
Epoch 30/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0634 - accuracy: 0.9810
Epoch 31/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0608 - accuracy: 0.9814
Epoch 32/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0579 - accuracy: 0.9815
Epoch 33/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0567 - accuracy: 0.9828
Epoch 34/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0555 - accuracy: 0.9810
Epoch 35/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0662 - accuracy: 0.9786
Epoch 36/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0533 - accuracy: 0.9830
Epoch 37/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0522 - accuracy: 0.9837
Epoch 38/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0501 - accuracy: 0.9842
Epoch 39/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0495 - accuracy: 0.9836
Epoch 40/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0515 - accuracy: 0.9831
Epoch 41/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0486 - accuracy: 0.9849
Epoch 42/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0566 - accuracy: 0.9816
Epoch 43/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0461 - accuracy: 0.9854
Epoch 44/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0458 - accuracy: 0.9845
Epoch 45/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0449 - accuracy: 0.9862
Epoch 46/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0467 - accuracy: 0.9848
Epoch 47/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0433 - accuracy: 0.9865
Epoch 48/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0436 - accuracy: 0.9867
Epoch 49/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0447 - accuracy: 0.9858
Epoch 50/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0417 - accuracy: 0.9865
Epoch 51/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0428 - accuracy: 0.9868
Epoch 52/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0413 - accuracy: 0.9880
Epoch 53/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0387 - accuracy: 0.9884
Epoch 54/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0387 - accuracy: 0.9872
Epoch 55/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0392 - accuracy: 0.9880
Epoch 56/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0406 - accuracy: 0.9867
Epoch 57/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0377 - accuracy: 0.9878
Epoch 58/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0383 - accuracy: 0.9870
Epoch 59/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0372 - accuracy: 0.9890
Epoch 60/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0341 - accuracy: 0.9891
Epoch 61/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0377 - accuracy: 0.9887
Epoch 62/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0345 - accuracy: 0.9890
Epoch 63/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0360 - accuracy: 0.9877
Epoch 64/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0355 - accuracy: 0.9890
Epoch 65/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0340 - accuracy: 0.9894
Epoch 66/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0344 - accuracy: 0.9892
Epoch 67/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0357 - accuracy: 0.9896
Epoch 68/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0372 - accuracy: 0.9881
Epoch 69/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0323 - accuracy: 0.9895
Epoch 70/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0308 - accuracy: 0.9897
Epoch 71/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0289 - accuracy: 0.9910
Epoch 72/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0306 - accuracy: 0.9910
Epoch 73/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0317 - accuracy: 0.9898
Epoch 74/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0318 - accuracy: 0.9903
Epoch 75/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0344 - accuracy: 0.9878
Epoch 76/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0293 - accuracy: 0.9901
Epoch 77/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0313 - accuracy: 0.9892
Epoch 78/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0263 - accuracy: 0.9919
Epoch 79/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0304 - accuracy: 0.9906
Epoch 80/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0265 - accuracy: 0.9914
Epoch 81/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0264 - accuracy: 0.9918
Epoch 82/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0275 - accuracy: 0.9909
Epoch 83/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0275 - accuracy: 0.9919
Epoch 84/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0276 - accuracy: 0.9906
Epoch 85/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0255 - accuracy: 0.9925
Epoch 86/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0254 - accuracy: 0.9910
Epoch 87/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0252 - accuracy: 0.9920
Epoch 88/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0257 - accuracy: 0.9908
Epoch 89/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0263 - accuracy: 0.9914
Epoch 90/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0251 - accuracy: 0.9926
Epoch 91/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0290 - accuracy: 0.9900
Epoch 92/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0278 - accuracy: 0.9920
Epoch 93/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0250 - accuracy: 0.9921
Epoch 94/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0261 - accuracy: 0.9915
Epoch 95/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0238 - accuracy: 0.9930
Epoch 96/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0227 - accuracy: 0.9929
Epoch 97/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0229 - accuracy: 0.9916
Epoch 98/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0240 - accuracy: 0.9920
Epoch 99/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0226 - accuracy: 0.9933
Epoch 100/100
329/329 [==============================] - 1s 2ms/step - loss: 0.0243 - accuracy: 0.9929

In [ ]:
test_loss, test_acc = model.evaluate(X_test, y_test , verbose=2)

print('\nTest accuracy:', test_acc)
print('\nTest Loss', test_loss)

141/141 - 0s - loss: 0.1774 - accuracy: 0.9716 - 275ms/epoch - 2ms/step

Test accuracy: 0.9715555310249329

Test Loss 0.1773984432220459

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred1 = model.predict(x_test)
y_pred1 = np.argmax(y_pred1,axis = 1)
cm = confusion_matrix(y_test,y_pred1)
print(cm)
print(accuracy_score(y_test,y_pred1))

[[3396    0]
 [1104    0]]
0.7546666666666667